### ISSUE TITLE
Duplicates in cluster navigation

### ISSUE THREAD

**Issue by fatm-dev** [Z3d0X/filament-fabricator#131]
It duplicates in cluster navigation window and shows one in default navigation window.

Version: 2.0.5
Filament Version: 3.2.9

![Screenshot 2024-01-22 at 11 25 11](https://github.com/Z3d0X/filament-fabricator/assets/29473101/467003f5-5e03-408b-93b6-6d9497e9aa47)

**Comment by Z3d0X** [comment]
Could you please share simple reproduction repository?

**Comment by Z3d0X** [comment]
Could be potentially fixed by #140
