### ISSUE TITLE
Spatie\Translatable

### ISSUE THREAD

**Issue by amrdesign** [Z3d0X/filament-fabricator#153]
Hello 
when i try use Spatie\Translatable\HasTranslations 

i add in model

    use HasTranslations;

    public array $translatable = [
        'title',
        'slug',
        'blocks',
    ];

i found error  when i try to edit page also not save block in first time only save in edit

![image](https://github.com/Z3d0X/filament-fabricator/assets/6537483/791e306f-bbd5-4cfd-b1f0-687ef46f79eb)

**Comment by Z3d0X** [comment]
This package, as of yet, doesn't support translations

**Comment by amrdesign** [comment]
I use this package
https://github.com/Astrotomic/laravel-translatable
its worked fine
![image](https://github.com/Z3d0X/filament-fabricator/assets/6537483/db6dfd95-3977-4588-8c53-de0cf5d57626)

**Comment by rasul-chopurov** [comment]
> I use this package https://github.com/Astrotomic/laravel-translatable its worked fine ![image](https://private-user-images.githubusercontent.com/6537483/324619832-db6dfd95-3977-4588-8c53-de0cf5d57626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTUwMjUsIm5iZiI6MTcxNDExNDcyNSwicGF0aCI6Ii82NTM3NDgzLzMyNDYxOTgzMi1kYjZkZmQ5NS0zOTc3LTQ1ODgtOGM1My1kZTBjZjVkNTc2MjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDY1ODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTk5N2M2NDFlMDgxZjhlNmExMmFmZDVkZmFlYTk5NGM0NTk1NjhmYjA3OTExN2RjNmM2NDY3YTJjNmI3NDUwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TSag_N_uqobCRE1Mv7jCux4dYG6MUdeOLImEo7feuNs)

how to modify is block layout?

**Comment by amrdesign** [comment]
@bahramzade I do not understand can explain

**Comment by rasul-chopurov** [comment]
> @bahramzadeне понимаю могу объяснить

            TextInput::make('title')->required()->translatable(),
            
            Not work, you use another translate plugin?

**Comment by rasul-chopurov** [comment]
> > I use this package https://github.com/Astrotomic/laravel-translatable its worked fine ![image](https://private-user-images.githubusercontent.com/6537483/324619832-db6dfd95-3977-4588-8c53-de0cf5d57626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTUwMjUsIm5iZiI6MTcxNDExNDcyNSwicGF0aCI6Ii82NTM3NDgzLzMyNDYxOTgzMi1kYjZkZmQ5NS0zOTc3LTQ1ODgtOGM1My1kZTBjZjVkNTc2MjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDY1ODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTk5N2M2NDFlMDgxZjhlNmExMmFmZDVkZmFlYTk5NGM0NTk1NjhmYjA3OTExN2RjNmM2NDY3YTJjNmI3NDUwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TSag_N_uqobCRE1Mv7jCux4dYG6MUdeOLImEo7feuNs)
> 
> how to modify is block layout?

+        'prefix' => App::currentLocale(), //?

**Comment by luckykenlin** [comment]
> I use this package https://github.com/Astrotomic/laravel-translatable its worked fine ![image](https://private-user-images.githubusercontent.com/6537483/324619832-db6dfd95-3977-4588-8c53-de0cf5d57626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODg5ODksIm5iZiI6MTcyMDQ4ODY4OSwicGF0aCI6Ii82NTM3NDgzLzMyNDYxOTgzMi1kYjZkZmQ5NS0zOTc3LTQ1ODgtOGM1My1kZTBjZjVkNTc2MjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDEzMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJiOTdmOWYxN2FhOWMzZGMxNjVkOWI3YzFhOWEzOGRjNjBhNzYxM2VlNzg5NTZlNTAzYmZlNjE3MGM1MWU4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._fw8dDcBWnuzDiIOWk0mTfdRg3mfSZlpedF6Q34N4nw)

Hi,  I am facing the same issue.    Can you explain more details how do you solve this with https://github.com/Astrotomic/laravel-translatable?    thanks

**Comment by sarsevanidze** [comment]
I have same issue, how you solved this ?

> @bahramzade I do not understand can explain
