### ISSUE TITLE
Using Fabricator with other models

### ISSUE THREAD

**Issue by Dontorpedo** [Z3d0X/filament-fabricator#26]
Hey, great plugin!

Is it possible to use the Fabricator with multiple models? would like to use it with pages and posts.. but didnt see anything in the documentation.

thanks

**Comment by Z3d0X** [comment]
Not yet supported, but i do plan to implement it in the future. It may take several weeks before this feature arrives

**Comment by Z3d0X** [comment]
see #44

**Comment by Z3d0X** [comment]
see #44
