### ISSUE TITLE
Creating Pages without slug

### ISSUE THREAD

**Issue by Dontorpedo** [Z3d0X/filament-fabricator#29]
Hi,

It seems that creating a page without a slug is not possible? i would like to create a home page..

also how would you do a blog with single post page? 

thanks for answers

**Comment by Z3d0X** [comment]
Use "/" as slug for home page

**Comment by Dontorpedo** [comment]
> Use "/" as slug for home page

ok, thank you.. and how about the single post page? is it possible to pass some data between pages?

**Comment by luckykenlin** [comment]
> > Use "/" as slug for home page
> 
> ok, thank you.. and how about the single post page? is it possible to pass some data between pages?

Did you solve this?
