### ISSUE TITLE
Deleted Block will make a page unrenderable

### ISSUE THREAD

**Issue by ijpatricio** [Z3d0X/filament-fabricator#39]
Hello @Z3d0X 

First, I want to thank you again for such a beautiful implementation of blocks in Filament!

So now, I ran into a problem: I deleted a block after a given page was saved into the database. 
I expected that the rendering mechanism ignored the JSON's non-existing blocks, but an exception was thrown. 

Is this the desired behavior?

Below is a screenshot and the video link at the timestamp where it happened. It's in Portuguese, but without sound, you realize what happened. After undeleting the block files, it went back to normal

https://youtu.be/4PGkwDa3B4s?t=4643

![image](https://user-images.githubusercontent.com/26031459/219306820-48b9c479-76f1-417f-a895-9331324d31e4.png)

**Comment by Z3d0X** [comment]
Hi sorry you ran into this issue. This is a bug yes, deleted blocks should be ignored.

I will work out a fix shortly.

Thank you for bringing this to my attention.

PS: I love the content you made featuring this plugin

**Comment by ijpatricio** [comment]
Oh, that's nothing. No worries!

PS: Thanks! And soon I'll make it in English also, so it can be viewed by a larger audience. Better to do it on V3, as it should come out in the next month(ish)?!?? 😄
