### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by martin-ro** [Z3d0X/filament-fabricator#49]
First of all, great plugin! Thanks for your work!

I noticed that queries in `PageBlocks` are fired every time you visit a page. Take for example this block:

```php
public static function getBlockSchema(): Block
    {
        return Block::make('my-block')
            ->schema([
                Select::make('users')
                    ->options(User::pluck('name', 'id'))
            ]);
    }

    public static function mutateData(array $data): array
    {
        return array_merge($data, [
            'users' => Cache::remember('my_block_users', 60, function () use ($data) {
                return User::find($data['users']);
            }),
        ]);
    }
```

When visiting the page, the mutated data is cached but the query for the`Select` (`User::pluck('name', 'id')`) field is still running every time. 

Cheers, Martin

**Comment by martin-ro** [comment]
Ok, so investigating this further... in `abstract class PageBlock` 

```php
public static function getName(): string
    {
        return static::getBlockSchema()->getName();
    }
```

is called which causes the queries to be run. For now, I can get around it by implementing `getName()` in each of my blocks and just returning a string.

**Comment by Z3d0X** [comment]
Passing a closure to `->options()` in `Select` ensures, that it is evaluated only when needed

```php
Select::make('users')
    ->options(fn () => User::pluck('name', 'id'))
```
