### ISSUE TITLE
Session empty on Fabricator Pages

### ISSUE THREAD

**Issue by chellmann** [Z3d0X/filament-fabricator#50]
Hi,

i have noticed that the Sessions seems to be Empty or not Set when a User visits a Page from the Fabricator.
I have tested this with a fresh and clean Installation of Laravel, Filament and this Package.

`@dump(auth())`

in the Layout-File returns "null", even when a User is logged in

I am wondering if anyone else can confirm this

Thanks!

**Comment by Z3d0X** [comment]
fixed in `v1.1.3`

https://github.com/Z3d0X/filament-fabricator/releases/tag/v1.1.3
